# Page settings
baseurl = "/"
title = "Always in Mind"
languageCode = "en-gb"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Steve Lee"
  description = "Developer of cognitive access tools @ OpenDirective"
  email = "steve@opendirective'.com"

  # Navigation
  [params.navigation]
    brand = "Always in Mind<p/><img src='images/AiM_Logo.png' />"
    zhome = ""
    work = "Work"
    testimonials = "Testimonials"
    zservices = ""
    about = "About"
    zcontact = ""

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    [[menu.prepend]]
      url = "#fh5co-services"
      name = "Features"
      weight = 10

    # postpended links
    [[menu.postpend]]
      url = "#fh5co-contact"
      name = "Find Out More"
      weight = 10

  # Hero section
  [params.hero]
    title = "Digital made easy"
    subtitle = "Some people find it difficult or daunting to engage in everyday digital activities, especially when faced with complex or confusing technology. People with dementia, learning disabilities or a brain injury may be unable to join in with their family and friend's on-line interactions.<br/><br/>Always in Mind helps overcome this barrier by providing simplified, friendly and safe access to every-day digital photos, videos, websites and emails."
    url = "#fh5co-contact"
    button = "Find Out More"

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Peace of Mind"
    description = "Stay in contact with relatives and friends to share experiences using digital photos, messages and more."
#    url = "#fh5co-contact"
#    button = "Find Out More"
    icon = "icon-share"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Easy Access"
    description = "Friendly, safe and personalised access means everyone can become more confident using digital technology."
#    url = "#fh5co-contact"
#    button = "Find Out More"
    icon = "icon-star"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Easy set-up"
    description = "Family, friends and supporters simply select media to share using existing digital social tools."
#    url = "#fh5co-contact"
#    button = "Find Out More"
    icon = "icon-bubbles"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch this video of Always In Mind"
    icon = "icon-play2"
    url = "https://alwaysinmind.info/images/demo.mp4"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Services section
  [params.services]
    enable = true
    title = "Always in Mind Features"
    description = "Always in Mind simplifies the use of existing web media and communication services like photos, videos and email. Family and friends use these services as usual and can mark items for sharing with the Always in Mind user or send them messages."

    [[params.services.item]]
      title = "Easy to Use"
      description = "Large touch buttons with clear text or pictures are organised into uncluttered screens with clearly signposted navigation."
      icon = "icon-star"

    [[params.services.item]]
      title = "Personalisation"
      description = "Options cater for individual user preferences and screen complexity that can be changed as requirments change."
      icon = "icon-settings"

    [[params.services.item]]
      title = "Built in reminders"
      description = "Help is always available at the touch of a button with text and speech reminders of what to do."
      icon = "icon-map"

    [[params.services.item]]
      title = "Connect through popular websites"
      description = "Privately communicate and share using popular websites such as Google or Facebook."
      icon = "icon-bubbles"

    [[params.services.item]]
      title = "Safe and secure"
      description = "Activities cannot cause damage to content and connections are safely restricted to people you trust."
      icon = "icon-key"

    [[params.services.item]]
      title = "Reliable service"
      description = "A fully supported web service using \"best of breed\" technologies and services.  Use any device with web access."
      icon = "icon-earphones-alt"

    [[params.services.item]]
      title = "Low cost"
      description = "Affordable subscription rates for easy access and no hassle cancellation."
      icon = "icon-wallet"

    [[params.services.item]]
      title = "Open for improvements"
      description = "Open source development means your ideas and contributions can improve easier access."
      icon = "icon-people"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = "yes"
    title = "Find out More"
    description = "Signup for our newsletter or try the demo."
    info = "Ways to find out more:"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-globe", '<a href="https://alwaysinmind.now.sh" target="_blank">Try the Demo</a>'],
        ["icon-github", '<a href="https://github.com/AlwaysInMind/aim-web-app/blob/master/README.md" target="_blank">See the Readme documentation</a>'],
        ["icon-twitter", '<a href="https://twitter.com/AlwaysInMind_" target="_blank">Follow us on Twitter</a>'],
        ["icon-envelope", '<a href="mailto:info@alwaysinmind.info?subject=Always in Mind query&amp;body=Your Message">Email info@alwaysinmind.info</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

    title2 = "Work with Us"
    description2 = "Join in our Mission to provide Simpler User Experiences."
    info2 = "Our Open Source project:"
    details2 = [
        ["icon-github", '<a href="https://github.com/AlwaysInMind" target="_blank">Join us on GitHub</a>'],
      ]

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; 2018 OpenDirective Ltd. All Rights Reserved. <br><span style="font-size:smaller">Based on a theme by FreeHTML, images: Pexels, plmd.me, Hugo port by: saey55</span>'
    links = [
        ["icon-twitter", "https://twitter.com/alwaysinmind_"],
#        ["icon-facebook", "#facebook"],
        ["icon-github", "https://github.com/AlwaysInMind"]
      ]
